### ISSUE TITLE
what is your project

### ISSUE THREAD

**Issue by Nikhilananddev** [Marken2808/AndroidApp#1]
**i want to contribute in your project**

**Comment by Marken2808** [comment]
Sorry for reply late, I am beginner in android. Just doing some small project like bus checker mostly in the UK. I can add you in if you interested

**Comment by nctune2808** [comment]
> **i want to contribute in your project**

Sorry for reply late, I am beginner in android. Just doing some small project like bus checker mostly in the UK. I can add you in if you interested
